//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ys.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ys.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to data source=(LocalDB)\v11.0;attachdbfilename=C:\Users\fatihemre\Documents\Visual Studio 2013\Projects\ys\ys\dbs\mssql.mdf.
        /// </summary>
        internal static string MsSQLConnectionString {
            get {
                return ResourceManager.GetString("MsSQLConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Customer WHERE Id = @Id.
        /// </summary>
        internal static string MsSQLDelete {
            get {
                return ResourceManager.GetString("MsSQLDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Customer (Id, FirstName, LastName, Email, Password, BirthDate) VALUES (@Id, @FirstName, @LastName, @Email, @Password, @BirthDate).
        /// </summary>
        internal static string MsSQLInsert {
            get {
                return ResourceManager.GetString("MsSQLInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [Id], [FirstName], [LastName], [Email], [Password], [BirthDate] FROM dbo.[Customer].
        /// </summary>
        internal static string MsSQLSelect {
            get {
                return ResourceManager.GetString("MsSQLSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Customer SET Id = @Id, FirstName = @FirstName, LastName = @LastName, Email = @Email, Password = @Password, BirthDate = @BirthDate WHERE Id = @Id.
        /// </summary>
        internal static string MsSQLUpdate {
            get {
                return ResourceManager.GetString("MsSQLUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to server=sql11.freemysqlhosting.net;uid=sql11156729;pwd=s6WrnFMGlC;database=sql11156729;.
        /// </summary>
        internal static string MySQLConnectionString {
            get {
                return ResourceManager.GetString("MySQLConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT c.user_id AS Id, c.name AS FirstName,&apos;&apos; AS LastName, c.email AS Email, c.password AS Password, ci.birthdate AS BirthDate FROM customer c INNER JOIN customer_info ci ON ci.user_id = c.user_id.
        /// </summary>
        internal static string MySQLSelect {
            get {
                return ResourceManager.GetString("MySQLSelect", resourceCulture);
            }
        }
    }
}
